### PR TITLE
Add supporter logos

### PR DESCRIPTION
**Pull request by vdemario**
- Created new "supporters" section below the silver sponsors with smaller images.
- Added InfoQ and StickerMule logos at the new supporters section.
- Centralized globo.com and Neoway logos.

Two issues popped up:

1. I can't run the site anymore using the most recent version of Hugo. I'd appreciate some help on this, I had to install 0.31 manually since that's what we use on the Dockerfile.
2. The English version didn't work locally so I don't know where to edit the sponsors section in that version.

### CODE REVIEW

**Comment by guilhermebr** [comment]
@vdemario for run the English version: `hugo server -v -w -t=gopherconbr --config=config_en.toml
`

**Comment by vdemario** [comment]
@andrewsmedina @guilhermebr do you want me to do the English version in this PR or a new one?

**Comment by andrewsmedina** [comment]
@vdemario you can do it in this PR if you want.

**Comment by vdemario** [comment]
I've submitted a change with the en-US version.

**Pull request merged**
